import { Button } from '@/components/common/Button';import { chooseAction,confirmAction } from '@/components/common/confirmationDialog';import { Screen } from '@/components/common/Screen';import { colors,shadow } from '@/constants/theme';import { parseImportJson } from '@/domain/validators/importData';import { useAppData } from '@/features/app/AppProvider';import { exportJsonFile,pickJsonFile } from '@/features/settings/dataTransfer';import { vocalMapRepository } from '@/repositories/LocalVocalMapRepository';import Constants from 'expo-constants';import React,{useState} from 'react';import { StyleSheet,Text,View } from 'react-native';
export default function SettingsScreen(){
  const {settings,saveSettings,refresh}=useAppData();
  const [message,setMessage]=useState('');
  const change=(key:'defaultFontSize'|'practiceFontSize',delta:number)=>void saveSettings({...settings,[key]:Math.max(14,Math.min(44,settings[key]+delta))});
  const exportData=async()=>{try{const data=await vocalMapRepository.exportData();await exportJsonFile(JSON.stringify(data,null,2));setMessage('バックアップを書き出しました。')}catch(e){setMessage(e instanceof Error?e.message:'エクスポートに失敗しました。')}};
  const importData=async()=>{try{
    const json=await pickJsonFile();if(!json)return;
    const result=parseImportJson(json);if(!result.valid){setMessage(result.message);return}
    const method=await chooseAction('読み込み方法を選択','追加は同じIDのデータだけ更新します。置き換えは現在の全データを消します。',[{label:'追加',value:'merge'},{label:'置き換え',value:'replace',destructive:true}] as const);
    if(!method)return;
    if(method==='replace'&&!await confirmAction('本当に置き換えますか？','現在のデータは元に戻せません。','置き換える',true))return;
    await vocalMapRepository.importData(result.data,method);await refresh();setMessage(method==='merge'?'データを追加しました。':'データを置き換えました。');
  }catch(e){setMessage(e instanceof Error?e.message:'インポートに失敗しました。')}};
  const reset=async()=>{if(!await confirmAction('プリセットを初期化しますか？','編集したプリセットが元に戻ります。','初期化'))return;await vocalMapRepository.resetPresetSymbols();await refresh();setMessage('プリセットを初期化しました。')};
  const clear=async()=>{if(!await confirmAction('全データを削除しますか？','曲、記号、設定がすべて削除されます。この操作は元に戻せません。','すべて削除',true))return;await vocalMapRepository.clearAll();await refresh();setMessage('全データを削除しました。')};
  return <Screen><Text style={styles.title}>設定</Text>{!!message&&<Text accessibilityRole="alert" style={styles.message}>{message}</Text>}<View style={styles.card}><Text style={styles.section}>文字サイズ</Text><SettingStepper label="編集画面" value={settings.defaultFontSize} onMinus={()=>change('defaultFontSize',-1)} onPlus={()=>change('defaultFontSize',1)}/><SettingStepper label="練習モード" value={settings.practiceFontSize} onMinus={()=>change('practiceFontSize',-2)} onPlus={()=>change('practiceFontSize',2)}/></View><View style={styles.card}><Text style={styles.section}>バックアップ</Text><Text style={styles.help}>曲、記号辞書、設定をschemaVersion付きJSONとして保存します。</Text><Button label="データをエクスポート" onPress={()=>void exportData()}/><Button label="データをインポート" variant="secondary" onPress={()=>void importData()}/></View><View style={styles.card}><Text style={styles.section}>初期化</Text><Button label="プリセット記号を初期化" variant="secondary" onPress={()=>void reset()}/><Button label="全データを削除" variant="danger" onPress={()=>void clear()}/></View><View style={styles.card}><Text style={styles.section}>プライバシー</Text><Text style={styles.help}>入力した歌詞と歌唱メモは端末内だけに保存されます。外部API、広告、分析、追跡、マイクは使用しません。歌詞は権利を守ってご自身で入力してください。</Text><Text style={styles.version}>Vocal Map バージョン {Constants.expoConfig?.version??'1.0.0'}</Text></View></Screen>
}
function SettingStepper({label,value,onMinus,onPlus}:{label:string;value:number;onMinus():void;onPlus():void}){return <View style={styles.stepper}><Text style={styles.settingLabel}>{label}</Text><Button label="−" variant="ghost" onPress={onMinus} accessibilityLabel={`${label}の文字を小さくする`}/><Text style={styles.value}>{value}px</Text><Button label="＋" variant="ghost" onPress={onPlus} accessibilityLabel={`${label}の文字を大きくする`}/></View>}
const styles=StyleSheet.create({title:{fontSize:28,fontWeight:'900',color:colors.text},message:{color:colors.primary,backgroundColor:colors.primarySoft,padding:12,borderRadius:10},card:{backgroundColor:colors.surface,borderRadius:16,padding:16,gap:12,...shadow},section:{fontSize:18,fontWeight:'800',color:colors.text},help:{color:colors.muted,lineHeight:21},stepper:{flexDirection:'row',alignItems:'center',gap:6,minHeight:48},settingLabel:{flex:1,color:colors.text,fontWeight:'700'},value:{minWidth:50,textAlign:'center',fontWeight:'800',color:colors.primary},version:{marginTop:8,fontSize:12,color:colors.muted}});
